### ISSUE TITLE
[💡 Feature request] create a copy to clipboard with the current informations on the page

### ISSUE THREAD

**Issue by paoloricciuti** [toniengelhardt/webapicheck#20]
One cool way to use this webapp would be to send it to non techincal users to get a report of their situation (useful for debugging)

The easiest way would be to include a copy to clipboard button that will copy the information in a dev digestable way. The step up could be add the ability to add a query parameter (reportTo) and onload send an email to it with the current information (so that one could just send a link with their email address setupped and immediately get back a feedback.

Obviosuly this second one it's far more expensive and it also has possible security implications to reason of but it could even be a form of profit for you (it could very easily become a paid feature but i don't know if that's where this project is headed).

If you are ok with those i can even start to work on those (to be fair i never used nuxt and i barely used vue but it shuldn't be to difficult and that is what code reviews are for right? RIGHT?)

Joking aside let me know what do you think about the proposal and let me know if you are ok with me working on them.

**Comment by toniengelhardt** [comment]
Amazing idea! I think maybe instead of email you could just download it into a JSON file instead with `file-saver` ? That You could then just attach the file to an email or send it however you like.

Would be absolutely amazing if you could work on it (also an amazing opportunity for you to get a look at Vue/Nuxt 😉). I'll then smooth out the edges if needed.

**Comment by paoloricciuti** [comment]
Well than it's not very different (if not more cumbersome) than copy...but i guess it's totally reasonable to not wanting an automatic email to go on whenever someone opens the page. I'd say we can start with the copy button.

What do you think the best format should be? I think it needs to be human readable more than machine readable since probably the developer reading it will need to scrim over the text by hand anyway.

Another cool way to do this however it's a share link with the current info encoded as a queryparameter that the user can share back to the dev (so that it also get an amazing ui and search capability). To encode the state we could use lz-string or, given that they are just booleans we could very easily do the bit trick to syntethize the state into a number (this would mean tho that every old url would be kinda invalid).

What do you think about this?

**Comment by toniengelhardt** [comment]
Yeah, I think the format could just be something like `{API name}: yes | no`, e.g.

```ts
Network Connection API: yes
Notifications API: no
...
```

The links could also be cool, but you have to see if the information fits into a URL. Atm there are 65 APIs, but the list is not complete yet and in the future there will hopefully be more.

**Comment by paoloricciuti** [comment]
Well with the bit trick it would be a number of 20 characters.

**Comment by paoloricciuti** [comment]
The trick i'm talking about is simply converting all the booleans to 0s and 1s and than converthing that binary number to decimal (if we want we could even go higher with the converted base to make sure that we stay with a reasonable small query parameter).

Minimal example

```ts
const apis={
    "Network Connection": true,
    "Notification API": false,
    "Geolocation API": true,
    "CookieStore": false,
}
```

would be converted to 1010 and than to 12 in decimal

upon receiving 12 as queryParam we just need to convert 12 back to binary and go char by char setting the correct value for the corresponding api.

**Comment by toniengelhardt** [comment]
Makes sense, but you need to add an ID (or index) to the APIs then, e.g. 1, 2, 3, ... to make sure that the sequence can be decoded. But I think that would be very cool, then you can just open the link and get the exact same view as the user.

**Comment by paoloricciuti** [comment]
I'm trying to think of a way to better organize this: adding the id would mean that every new api would need an id added by hand and that's error prone. lz-string would produce a 993 length string which is still well below the 2048 limit for the url but it might still be super long.

I'll reason about it and check back here.

**Comment by toniengelhardt** [comment]
Great! 

But why would it be 993 chars long? Should be one char per API max or `num_apis/4` if encoded as hex char no?

**Comment by paoloricciuti** [comment]
I was talking about the lz-string representation of the object...maybe I can trim that down by simply encoding the name of the api + a single number...I have to experiment with it

**Comment by paoloricciuti** [comment]
But I have to guess the greater part would be the name of the api's...maybe that could be trimmed down by finding the shortest amount of characters to uniquely identify a key

**Comment by toniengelhardt** [comment]
I think the simplest solution would be to just manually assign all the APIs a running number in the order in which they are added and then you just get a string like `0010 1101 1100 01...` that you can encode with 1 letter per 4 flags, aka. `0010` becomes alphabet index `2` or `b`, the rest of `sequence.length % 4` stays 0 and 1, so you get for the sequence above `bml01`. That way it stays super short and we can encode even more info like device, browser, etc.

**Comment by paoloricciuti** [comment]
The thing that scares me is that when you add a new api you have to scroll through the whole list, find the highest number and manually add the new id from there. If the contributor insert an already present number without noticing it could be a problem

**Comment by toniengelhardt** [comment]
It's true. You could add new ones always at the bottom, but it's not ideal.

**Comment by paoloricciuti** [comment]
I was thinking that maybe the best way to handle this without sacrificing the DX is to let contributors add the date of addition (easier than the incremental id)...and maybe add a node script and a github action that checks that the diff contains a date. If you are ok with this i'll start work on it.

**Comment by toniengelhardt** [comment]
But what would you do with the existing ones? 

Maybe the most explicit thing would be to just define an export list like:

```ts
/**
 * IMPORTANT
 * Don't reorder and always add new entries at the bottom, otherwise existing links will break. 
 */
const webApiExportList = [
  'accelerometer',
  'notifications-api',
  // ...
]
```

That way it is more flexible and independent from everything else in case we need to refactor anything at some point.

And then we add a test that makes sure that all APIs in `webApiData` are included in the export list, otherwise fails.

DX impact would be minimal, when you add a new API you just have to add the `id` to the export list and that's it.

**Comment by paoloricciuti** [comment]
I like this idea...and we can just use the index as the Id.

**Comment by toniengelhardt** [comment]
Exactly, let's do it!
